
["Scenic Config"]
	#A comma-separated list of strings of dimensions in which Scenic's features should generate (strings from BiomeDictionary.Type, see below for the format)
	dimensionWhitelist = ["OVERWORLD", "TWILIGHT"]
	#Maximum Short Grass Blocks Per Chunk (in blocks) - set to zero to disable
	maximumGrassShorts = 5
	#Maximum Grass Tufts Per Chunk (in blocks) - set to zero to disable
	maximumGrassTufts = 5
	#Maximum Rocky Dirt Blocks Per Chunk (in blocks) - set to zero to disable
	maximumRockyDirt = 8
	#Maximum Stalactites Per Chunk (in blocks) - set to zero to disable
	maximumStalactites = 10
	#Maximum Stalagmites Per Chunk (in blocks) - set to zero to disable
	maximumStalagmites = 10
	#Maximum Mossy Gravel Blocks Per Chunk (in blocks) - set to zero to disable
	maximumMossyGravel = 1
	#Maximum Mossy Rocky Dirt Blocks Per Chunk (in blocks) - set to zero to disable
	maximumMossyRockyDirt = 1
	#Maximum Treasure Pots Per Chunk (in blocks) - set to zero to disable
	maximumTreasurePots = 20
	#Maximum Fish Bones Per Chunk (in blocks) - set to zero to disable
	maximumFishBones = 1
	#Maximum Roots Per Chunk (in blocks) - set to zero to disable
	maximumRoots = 12
	#Maximum Roots Per Chunk (in blocks) - set to zero to disable
	maximumRootsLong = 15
	#Maximum Roots Per Chunk (in blocks) - set to zero to disable
	maximumRootsGround = 2

